SELECT DISTINCT
	?nodeId
	(SAMPLE(?description) AS ?description)
	(SAMPLE(?name) as ?name)
	(SAMPLE(?image) as ?image)
	(SAMPLE(?startDate) as ?startDate)
	WHERE {
		?nodeId a schema:${category} .
			?nodeId schema:name ?name .
			?nodeId schema:description ?description .
			?nodeId schema:image ?imgObj .
			?imgObj a schema:ImageObject .
			?imgObj schema:url ?image .
			?nodeId schema:startDate ?startDate .
	}
	GROUP BY ?nodeId
	LIMIT 10
